#!/bin/bash

warned=0
function warn {
  echo "$1"
  warned=1
}

function check_clang_format {
  git show ":$1" | \
    clang-format --style=file --output-replacements-xml | \
    grep -q "<replacement "
  [[ $? -ne 0 ]]
}

function check_buildifier {
  git show ":$1" | \
    buildifier --mode=check --type=build >/dev/null 2>&1
}

files=$(git diff --cached --name-only --diff-filter=ACMRT)
for file in ${files} ; do
  if [[ "$file" =~ \.cc$|\.h$ ]] ; then
    check_clang_format "$file" || warn "Needs clang-format: $file"
  fi

  if [[ "$file" =~ BUILD.bazel$ ]] ; then
    check_buildifier "$file" || warn "Needs buildifier: $file"
  fi

  if [[ ! "$file" =~ ^git/ ]] ; then
    grep --quiet MTS "$file" && warn "Contains MTS: $file"
  fi
done

exit $warned
