#!/bin/bash

TREE=left_tree
TREEDIR=${HOME}/xmaslights/${TREE}

bazel run cmd/calc -- \
	--input_coords=${TREEDIR}/3dpoints.textproto  \
	--camera_metadata=${TREEDIR}/camera_metadata.textproto \
	--output_coords=${TREEDIR}/3dpoints.textproto \
	"$@"
